CREATE DATABASE IF NOT EXISTS mis_core_db;
CREATE DATABASE IF NOT EXISTS mis_energy_db;
CREATE DATABASE IF NOT EXISTS mis_ai_db;
CREATE DATABASE IF NOT EXISTS mis_changeover_db;

GRANT ALL PRIVILEGES ON mis_changeover_db.* TO 'mis'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'mis'@'%';
FLUSH PRIVILEGES;
