version: '3.8'
services:
  nginx-proxy:
    build: .
    image: meu-proxy:producao  # <--- ADICIONE ESTA LINHA
    container_name: 01_proxy_reverse
    ports:
      - "3000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always