# Generated by Django 5.0 on 2025-12-30 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0027_remove_tagcoleta_conexao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome descritivo do perfil (ex: 'Análise OEE Velocidade')", max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional do objetivo da análise')),
                ('config', models.JSONField(help_text='Configuração completa do estado Analytics')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.CharField(blank=True, help_text='Usuário que criou o perfil (opcional)', max_length=50)),
                ('linha', models.ForeignKey(help_text='Linha a qual este perfil pertence', on_delete=django.db.models.deletion.CASCADE, related_name='analytics_profiles', to='equipamentos.linhaproducao')),
            ],
            options={
                'verbose_name': 'Perfil de Analytics',
                'verbose_name_plural': 'Perfis de Analytics',
                'ordering': ['-atualizado_em'],
                'unique_together': {('linha', 'nome')},
            },
        ),
    ]
