[OK]"[OK]"[OK]"[OK]
[OK]S[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK] [OK]-[OK] [OK]E[OK]x[OK]e[OK]c[OK]u[OK]t[OK]a[OK] [OK]a[OK]g[OK]r[OK]e[OK]g[OK]a[OK]ç[OK]õ[OK]e[OK]s[OK] [OK]e[OK]m[OK] [OK]i[OK]n[OK]t[OK]e[OK]r[OK]v[OK]a[OK]l[OK]o[OK]s[OK] [OK]r[OK]e[OK]g[OK]u[OK]l[OK]a[OK]r[OK]e[OK]s[OK]
[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]=[OK]
[OK]"[OK]"[OK]"[OK]
[OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]l[OK]o[OK]g[OK]g[OK]i[OK]n[OK]g[OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]s[OK]y[OK]s[OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]a[OK]p[OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK].[OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK]s[OK].[OK]b[OK]a[OK]c[OK]k[OK]g[OK]r[OK]o[OK]u[OK]n[OK]d[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]B[OK]a[OK]c[OK]k[OK]g[OK]r[OK]o[OK]u[OK]n[OK]d[OK]S[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]a[OK]p[OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK].[OK]t[OK]r[OK]i[OK]g[OK]g[OK]e[OK]r[OK]s[OK].[OK]c[OK]r[OK]o[OK]n[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]C[OK]r[OK]o[OK]n[OK]T[OK]r[OK]i[OK]g[OK]g[OK]e[OK]r[OK]
[OK]
[OK]#[OK] [OK]C[OK]o[OK]n[OK]f[OK]i[OK]g[OK]u[OK]r[OK]a[OK]r[OK] [OK]D[OK]j[OK]a[OK]n[OK]g[OK]o[OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]o[OK]s[OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]d[OK]j[OK]a[OK]n[OK]g[OK]o[OK]
[OK]o[OK]s[OK].[OK]e[OK]n[OK]v[OK]i[OK]r[OK]o[OK]n[OK].[OK]s[OK]e[OK]t[OK]d[OK]e[OK]f[OK]a[OK]u[OK]l[OK]t[OK]([OK]'[OK]D[OK]J[OK]A[OK]N[OK]G[OK]O[OK]_[OK]S[OK]E[OK]T[OK]T[OK]I[OK]N[OK]G[OK]S[OK]_[OK]M[OK]O[OK]D[OK]U[OK]L[OK]E[OK]'[OK],[OK] [OK]'[OK]s[OK]e[OK]u[OK]_[OK]p[OK]r[OK]o[OK]j[OK]e[OK]t[OK]o[OK].[OK]s[OK]e[OK]t[OK]t[OK]i[OK]n[OK]g[OK]s[OK]'[OK])[OK]
[OK]d[OK]j[OK]a[OK]n[OK]g[OK]o[OK].[OK]s[OK]e[OK]t[OK]u[OK]p[OK]([OK])[OK]
[OK]
[OK]f[OK]r[OK]o[OK]m[OK] [OK]a[OK]g[OK]r[OK]e[OK]g[OK]a[OK]d[OK]o[OK]r[OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]a[OK]g[OK]r[OK]e[OK]g[OK]a[OK]d[OK]o[OK]r[OK]
[OK]
[OK]#[OK] [OK]=[OK]=[OK]=[OK]=[OK]=[OK] [OK]C[OK]O[OK]N[OK]F[OK]I[OK]G[OK]U[OK]R[OK]A[OK]Ç[OK]Ã[OK]O[OK] [OK]D[OK]E[OK] [OK]L[OK]O[OK]G[OK]G[OK]I[OK]N[OK]G[OK] [OK]=[OK]=[OK]=[OK]=[OK]=[OK]
[OK]l[OK]o[OK]g[OK]g[OK]i[OK]n[OK]g[OK].[OK]b[OK]a[OK]s[OK]i[OK]c[OK]C[OK]o[OK]n[OK]f[OK]i[OK]g[OK]([OK]
[OK] [OK] [OK] [OK] [OK]l[OK]e[OK]v[OK]e[OK]l[OK]=[OK]l[OK]o[OK]g[OK]g[OK]i[OK]n[OK]g[OK].[OK]I[OK]N[OK]F[OK]O[OK],[OK]
[OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK]m[OK]a[OK]t[OK]=[OK]'[OK]%[OK]([OK]a[OK]s[OK]c[OK]t[OK]i[OK]m[OK]e[OK])[OK]s[OK] [OK]-[OK] [OK]%[OK]([OK]n[OK]a[OK]m[OK]e[OK])[OK]s[OK] [OK]-[OK] [OK]%[OK]([OK]l[OK]e[OK]v[OK]e[OK]l[OK]n[OK]a[OK]m[OK]e[OK])[OK]s[OK] [OK]-[OK] [OK]%[OK]([OK]m[OK]e[OK]s[OK]s[OK]a[OK]g[OK]e[OK])[OK]s[OK]'[OK],[OK]
[OK] [OK] [OK] [OK] [OK]h[OK]a[OK]n[OK]d[OK]l[OK]e[OK]r[OK]s[OK]=[OK][[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]i[OK]n[OK]g[OK].[OK]F[OK]i[OK]l[OK]e[OK]H[OK]a[OK]n[OK]d[OK]l[OK]e[OK]r[OK]([OK]'[OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK].[OK]l[OK]o[OK]g[OK]'[OK])[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]i[OK]n[OK]g[OK].[OK]S[OK]t[OK]r[OK]e[OK]a[OK]m[OK]H[OK]a[OK]n[OK]d[OK]l[OK]e[OK]r[OK]([OK]s[OK]y[OK]s[OK].[OK]s[OK]t[OK]d[OK]o[OK]u[OK]t[OK])[OK]
[OK] [OK] [OK] [OK] [OK]][OK]
[OK])[OK]
[OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK] [OK]=[OK] [OK]l[OK]o[OK]g[OK]g[OK]i[OK]n[OK]g[OK].[OK]g[OK]e[OK]t[OK]L[OK]o[OK]g[OK]g[OK]e[OK]r[OK]([OK]'[OK]S[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK]'[OK])[OK]
[OK]
[OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK] [OK]=[OK] [OK]B[OK]a[OK]c[OK]k[OK]g[OK]r[OK]o[OK]u[OK]n[OK]d[OK]S[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK]([OK])[OK]
[OK]
[OK]
[OK]d[OK]e[OK]f[OK] [OK]i[OK]n[OK]i[OK]c[OK]i[OK]a[OK]r[OK]_[OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK]([OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]I[OK]n[OK]i[OK]c[OK]i[OK]a[OK] [OK]o[OK] [OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK] [OK]d[OK]e[OK] [OK]a[OK]g[OK]r[OK]e[OK]g[OK]a[OK]ç[OK]õ[OK]e[OK]s[OK]"[OK]"[OK]"[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK].[OK]r[OK]u[OK]n[OK]n[OK]i[OK]n[OK]g[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]w[OK]a[OK]r[OK]n[OK]i[OK]n[OK]g[OK]([OK]"[OK]S[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK] [OK]j[OK]á[OK] [OK]e[OK]s[OK]t[OK]á[OK] [OK]r[OK]o[OK]d[OK]a[OK]n[OK]d[OK]o[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]t[OK]u[OK]r[OK]n[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]=[OK]"[OK] [OK]*[OK] [OK]6[OK]0[OK])[OK]
[OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]I[OK]N[OK]I[OK]C[OK]I[OK]A[OK]N[OK]D[OK]O[OK] [OK]S[OK]C[OK]H[OK]E[OK]D[OK]U[OK]L[OK]E[OK]R[OK] [OK]D[OK]E[OK] [OK]A[OK]G[OK]R[OK]E[OK]G[OK]A[OK]Ç[OK]Õ[OK]E[OK]S[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]=[OK]"[OK] [OK]*[OK] [OK]6[OK]0[OK])[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]A[OK]g[OK]r[OK]e[OK]g[OK]a[OK] [OK]ú[OK]l[OK]t[OK]i[OK]m[OK]a[OK] [OK]h[OK]o[OK]r[OK]a[OK] [OK]a[OK] [OK]c[OK]a[OK]d[OK]a[OK] [OK]h[OK]o[OK]r[OK]a[OK] [OK]([OK]n[OK]o[OK] [OK]m[OK]i[OK]n[OK]u[OK]t[OK]o[OK] [OK]5[OK])[OK]
[OK] [OK] [OK] [OK] [OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK].[OK]a[OK]d[OK]d[OK]_[OK]j[OK]o[OK]b[OK]([OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]g[OK]r[OK]e[OK]g[OK]a[OK]d[OK]o[OK]r[OK].[OK]a[OK]g[OK]r[OK]e[OK]g[OK]a[OK]r[OK]_[OK]u[OK]l[OK]t[OK]i[OK]m[OK]a[OK]_[OK]h[OK]o[OK]r[OK]a[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]C[OK]r[OK]o[OK]n[OK]T[OK]r[OK]i[OK]g[OK]g[OK]e[OK]r[OK]([OK]m[OK]i[OK]n[OK]u[OK]t[OK]e[OK]=[OK]5[OK])[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]d[OK]=[OK]'[OK]a[OK]g[OK]r[OK]e[OK]g[OK]a[OK]r[OK]_[OK]h[OK]o[OK]r[OK]a[OK]'[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]n[OK]a[OK]m[OK]e[OK]=[OK]'[OK]A[OK]g[OK]r[OK]e[OK]g[OK]a[OK]r[OK] [OK]ú[OK]l[OK]t[OK]i[OK]m[OK]a[OK] [OK]h[OK]o[OK]r[OK]a[OK]'[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]p[OK]l[OK]a[OK]c[OK]e[OK]_[OK]e[OK]x[OK]i[OK]s[OK]t[OK]i[OK]n[OK]g[OK]=[OK]T[OK]r[OK]u[OK]e[OK]
[OK] [OK] [OK] [OK] [OK])[OK]
[OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✓[OK] [OK]J[OK]o[OK]b[OK] [OK]H[OK]O[OK]R[OK]A[OK] [OK]a[OK]g[OK]e[OK]n[OK]d[OK]a[OK]d[OK]o[OK] [OK]([OK]m[OK]i[OK]n[OK]u[OK]t[OK]o[OK] [OK]5[OK] [OK]d[OK]e[OK] [OK]c[OK]a[OK]d[OK]a[OK] [OK]h[OK]o[OK]r[OK]a[OK])[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]A[OK]g[OK]r[OK]e[OK]g[OK]a[OK] [OK]ú[OK]l[OK]t[OK]i[OK]m[OK]o[OK] [OK]t[OK]u[OK]r[OK]n[OK]o[OK] [OK]a[OK] [OK]c[OK]a[OK]d[OK]a[OK] [OK]1[OK] [OK]h[OK]o[OK]r[OK]a[OK] [OK]([OK]n[OK]o[OK] [OK]m[OK]i[OK]n[OK]u[OK]t[OK]o[OK] [OK]1[OK]0[OK])[OK]
[OK] [OK] [OK] [OK] [OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK].[OK]a[OK]d[OK]d[OK]_[OK]j[OK]o[OK]b[OK]([OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]g[OK]r[OK]e[OK]g[OK]a[OK]d[OK]o[OK]r[OK].[OK]a[OK]g[OK]r[OK]e[OK]g[OK]a[OK]r[OK]_[OK]u[OK]l[OK]t[OK]i[OK]m[OK]o[OK]_[OK]t[OK]u[OK]r[OK]n[OK]o[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]C[OK]r[OK]o[OK]n[OK]T[OK]r[OK]i[OK]g[OK]g[OK]e[OK]r[OK]([OK]m[OK]i[OK]n[OK]u[OK]t[OK]e[OK]=[OK]1[OK]0[OK])[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]d[OK]=[OK]'[OK]a[OK]g[OK]r[OK]e[OK]g[OK]a[OK]r[OK]_[OK]t[OK]u[OK]r[OK]n[OK]o[OK]'[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]n[OK]a[OK]m[OK]e[OK]=[OK]'[OK]A[OK]g[OK]r[OK]e[OK]g[OK]a[OK]r[OK] [OK]ú[OK]l[OK]t[OK]i[OK]m[OK]o[OK] [OK]t[OK]u[OK]r[OK]n[OK]o[OK]'[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]p[OK]l[OK]a[OK]c[OK]e[OK]_[OK]e[OK]x[OK]i[OK]s[OK]t[OK]i[OK]n[OK]g[OK]=[OK]T[OK]r[OK]u[OK]e[OK]
[OK] [OK] [OK] [OK] [OK])[OK]
[OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✓[OK] [OK]J[OK]o[OK]b[OK] [OK]T[OK]U[OK]R[OK]N[OK]O[OK] [OK]a[OK]g[OK]e[OK]n[OK]d[OK]a[OK]d[OK]o[OK] [OK]([OK]m[OK]i[OK]n[OK]u[OK]t[OK]o[OK] [OK]1[OK]0[OK] [OK]d[OK]e[OK] [OK]c[OK]a[OK]d[OK]a[OK] [OK]h[OK]o[OK]r[OK]a[OK])[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]#[OK] [OK]A[OK]g[OK]r[OK]e[OK]g[OK]a[OK] [OK]d[OK]i[OK]a[OK] [OK]a[OK]n[OK]t[OK]e[OK]r[OK]i[OK]o[OK]r[OK] [OK]t[OK]o[OK]d[OK]o[OK]s[OK] [OK]o[OK]s[OK] [OK]d[OK]i[OK]a[OK]s[OK] [OK]à[OK]s[OK] [OK]0[OK]0[OK]:[OK]3[OK]0[OK]
[OK] [OK] [OK] [OK] [OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK].[OK]a[OK]d[OK]d[OK]_[OK]j[OK]o[OK]b[OK]([OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]a[OK]g[OK]r[OK]e[OK]g[OK]a[OK]d[OK]o[OK]r[OK].[OK]a[OK]g[OK]r[OK]e[OK]g[OK]a[OK]r[OK]_[OK]d[OK]i[OK]a[OK]_[OK]a[OK]n[OK]t[OK]e[OK]r[OK]i[OK]o[OK]r[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]C[OK]r[OK]o[OK]n[OK]T[OK]r[OK]i[OK]g[OK]g[OK]e[OK]r[OK]([OK]h[OK]o[OK]u[OK]r[OK]=[OK]0[OK],[OK] [OK]m[OK]i[OK]n[OK]u[OK]t[OK]e[OK]=[OK]3[OK]0[OK])[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]d[OK]=[OK]'[OK]a[OK]g[OK]r[OK]e[OK]g[OK]a[OK]r[OK]_[OK]d[OK]i[OK]a[OK]'[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]n[OK]a[OK]m[OK]e[OK]=[OK]'[OK]A[OK]g[OK]r[OK]e[OK]g[OK]a[OK]r[OK] [OK]d[OK]i[OK]a[OK] [OK]a[OK]n[OK]t[OK]e[OK]r[OK]i[OK]o[OK]r[OK]'[OK],[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]p[OK]l[OK]a[OK]c[OK]e[OK]_[OK]e[OK]x[OK]i[OK]s[OK]t[OK]i[OK]n[OK]g[OK]=[OK]T[OK]r[OK]u[OK]e[OK]
[OK] [OK] [OK] [OK] [OK])[OK]
[OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✓[OK] [OK]J[OK]o[OK]b[OK] [OK]D[OK]I[OK]A[OK] [OK]a[OK]g[OK]e[OK]n[OK]d[OK]a[OK]d[OK]o[OK] [OK]([OK]0[OK]0[OK]:[OK]3[OK]0[OK] [OK]t[OK]o[OK]d[OK]o[OK]s[OK] [OK]o[OK]s[OK] [OK]d[OK]i[OK]a[OK]s[OK])[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK].[OK]s[OK]t[OK]a[OK]r[OK]t[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✓[OK] [OK]S[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK] [OK]i[OK]n[OK]i[OK]c[OK]i[OK]a[OK]d[OK]o[OK] [OK]c[OK]o[OK]m[OK] [OK]s[OK]u[OK]c[OK]e[OK]s[OK]s[OK]o[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]=[OK]"[OK] [OK]*[OK] [OK]6[OK]0[OK])[OK]
[OK]
[OK]
[OK]d[OK]e[OK]f[OK] [OK]p[OK]a[OK]r[OK]a[OK]r[OK]_[OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK]([OK])[OK]:[OK]
[OK] [OK] [OK] [OK] [OK]"[OK]"[OK]"[OK]P[OK]a[OK]r[OK]a[OK] [OK]o[OK] [OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK]"[OK]"[OK]"[OK]
[OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK].[OK]r[OK]u[OK]n[OK]n[OK]i[OK]n[OK]g[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK].[OK]s[OK]h[OK]u[OK]t[OK]d[OK]o[OK]w[OK]n[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]✓[OK] [OK]S[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK] [OK]p[OK]a[OK]r[OK]a[OK]d[OK]o[OK]"[OK])[OK]
[OK]
[OK]
[OK]i[OK]f[OK] [OK]_[OK]_[OK]n[OK]a[OK]m[OK]e[OK]_[OK]_[OK] [OK]=[OK]=[OK] [OK]'[OK]_[OK]_[OK]m[OK]a[OK]i[OK]n[OK]_[OK]_[OK]'[OK]:[OK]
[OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]I[OK]n[OK]i[OK]c[OK]i[OK]a[OK]n[OK]d[OK]o[OK] [OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK] [OK]m[OK]a[OK]n[OK]u[OK]a[OK]l[OK]m[OK]e[OK]n[OK]t[OK]e[OK].[OK].[OK].[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK]i[OK]n[OK]i[OK]c[OK]i[OK]a[OK]r[OK]_[OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK]([OK])[OK]
[OK] [OK] [OK] [OK] [OK]
[OK] [OK] [OK] [OK] [OK]t[OK]r[OK]y[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]#[OK] [OK]M[OK]a[OK]n[OK]t[OK]é[OK]m[OK] [OK]o[OK] [OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK] [OK]r[OK]o[OK]d[OK]a[OK]n[OK]d[OK]o[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]t[OK]i[OK]m[OK]e[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]w[OK]h[OK]i[OK]l[OK]e[OK] [OK]T[OK]r[OK]u[OK]e[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]i[OK]m[OK]e[OK].[OK]s[OK]l[OK]e[OK]e[OK]p[OK]([OK]1[OK])[OK]
[OK] [OK] [OK] [OK] [OK]e[OK]x[OK]c[OK]e[OK]p[OK]t[OK] [OK]K[OK]e[OK]y[OK]b[OK]o[OK]a[OK]r[OK]d[OK]I[OK]n[OK]t[OK]e[OK]r[OK]r[OK]u[OK]p[OK]t[OK]:[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]l[OK]o[OK]g[OK]g[OK]e[OK]r[OK].[OK]i[OK]n[OK]f[OK]o[OK]([OK]"[OK]I[OK]n[OK]t[OK]e[OK]r[OK]r[OK]u[OK]p[OK]ç[OK]ã[OK]o[OK] [OK]d[OK]o[OK] [OK]u[OK]s[OK]u[OK]á[OK]r[OK]i[OK]o[OK] [OK]d[OK]e[OK]t[OK]e[OK]c[OK]t[OK]a[OK]d[OK]a[OK]"[OK])[OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]a[OK]r[OK]a[OK]r[OK]_[OK]s[OK]c[OK]h[OK]e[OK]d[OK]u[OK]l[OK]e[OK]r[OK]([OK])[OK]
