# Generated by Django 5.0 on 2025-11-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0016_ordemproducao_producao_realizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Iniciativa')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='NAO_INICIADO', max_length=20, verbose_name='Status')),
                ('responsavel', models.CharField(blank=True, max_length=100, verbose_name='Responsável')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Iniciativa Estratégica',
                'verbose_name_plural': 'Iniciativas Estratégicas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
