# Generated by Django 5.0 on 2025-12-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0019_alter_sensor_tipo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="lsl",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="LSL (Limite Inferior de Especificação)",
            ),
        ),
        migrations.AddField(
            model_name="sensor",
            name="nominal",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Valor Nominal (Target)"
            ),
        ),
        migrations.AddField(
            model_name="sensor",
            name="usl",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="USL (Limite Superior de Especificação)",
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="valor_max",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Valor Máximo (Gauge)"
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="valor_min",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Valor Mínimo (Gauge)"
            ),
        ),
    ]
