# Generated by Django 5.0 on 2025-11-14 22:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinhaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código da Linha')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Linha')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('localizacao', models.CharField(max_length=200, verbose_name='Localização')),
                ('ativa', models.BooleanField(default=True, verbose_name='Linha Ativa')),
                ('velocidade_planejada', models.FloatField(help_text='Velocidade planejada da linha completa', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Velocidade Planejada (unid/min)')),
                ('meta_producao_hora', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Meta Produção/Hora')),
                ('meta_producao_turno', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Meta Produção/Turno (8h)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Linha de Produção',
                'verbose_name_plural': 'Linhas de Produção',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Equipamento')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('ENCHEDORA', 'Enchedora'), ('BALANCA', 'Balança'), ('ENCAIXOTADORA', 'Encaixotadora'), ('ENVOLVEDORA', 'Envolvedora')], max_length=20, verbose_name='Tipo')),
                ('ordem_na_linha', models.IntegerField(default=1, help_text='Posição do equipamento na sequência da linha (1, 2, 3...)', verbose_name='Ordem na Linha')),
                ('localizacao', models.CharField(max_length=200, verbose_name='Localização')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('MANUTENCAO', 'Em Manutenção')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('velocidade_nominal', models.FloatField(help_text='Velocidade nominal do equipamento', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Velocidade Nominal (unid/min)')),
                ('velocidade_maxima', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Velocidade Máxima (unid/min)')),
                ('temperatura_min', models.FloatField(blank=True, null=True, verbose_name='Temp. Mínima (°C)')),
                ('temperatura_max', models.FloatField(blank=True, null=True, verbose_name='Temp. Máxima (°C)')),
                ('pressao_min', models.FloatField(blank=True, null=True, verbose_name='Pressão Mínima (PSI)')),
                ('pressao_max', models.FloatField(blank=True, null=True, verbose_name='Pressão Máxima (PSI)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='equipamentos.linhaproducao', verbose_name='Linha de Produção')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['linha', 'ordem_na_linha'],
            },
        ),
        migrations.CreateModel(
            name='Defeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('tipo_defeito', models.CharField(max_length=100, verbose_name='Tipo de Defeito')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('quantidade', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('severidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20, verbose_name='Severidade')),
                ('resolvido', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defeitos', to='equipamentos.equipamento', verbose_name='Equipamento')),
                ('linha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defeitos', to='equipamentos.linhaproducao', verbose_name='Linha')),
            ],
            options={
                'verbose_name': 'Defeito',
                'verbose_name_plural': 'Defeitos',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código do Sensor')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Sensor')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Sensor de Entrada'), ('SAIDA', 'Sensor de Saída'), ('TEMPERATURA', 'Sensor de Temperatura'), ('PRESSAO', 'Sensor de Pressão'), ('VELOCIDADE', 'Sensor de Velocidade'), ('NIVEL', 'Sensor de Nível')], max_length=20, verbose_name='Tipo')),
                ('tag_influxdb', models.CharField(help_text='Nome do campo no InfluxDB (ex: contagem_entrada, temperatura)', max_length=100, verbose_name='Tag InfluxDB')),
                ('unidade', models.CharField(blank=True, max_length=20, verbose_name='Unidade de Medida')),
                ('ativo', models.BooleanField(default=True, verbose_name='Sensor Ativo')),
                ('valor_min', models.FloatField(blank=True, null=True, verbose_name='Valor Mínimo')),
                ('valor_max', models.FloatField(blank=True, null=True, verbose_name='Valor Máximo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='equipamentos.equipamento', verbose_name='Equipamento')),
                ('linha', models.ForeignKey(blank=True, help_text='Para sensores de entrada/saída da linha inteira', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='equipamentos.linhaproducao', verbose_name='Linha de Produção')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'ordering': ['linha', 'equipamento', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='MetricaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(db_index=True, verbose_name='Data/Hora')),
                ('periodo', models.CharField(choices=[('HORA', 'Hora'), ('TURNO', 'Turno'), ('DIA', 'Dia'), ('SEMANA', 'Semana')], default='HORA', max_length=20, verbose_name='Período')),
                ('turno', models.CharField(blank=True, max_length=20, verbose_name='Turno')),
                ('contagem_entrada', models.IntegerField(default=0, verbose_name='Contagem Entrada')),
                ('contagem_saida', models.IntegerField(default=0, verbose_name='Contagem Saída')),
                ('descarte', models.IntegerField(default=0, verbose_name='Descarte')),
                ('percentual_descarte', models.FloatField(default=0.0, verbose_name='% Descarte')),
                ('velocidade_planejada', models.FloatField(default=0.0, verbose_name='Velocidade Planejada')),
                ('velocidade_real', models.FloatField(default=0.0, verbose_name='Velocidade Real')),
                ('tempo_producao', models.FloatField(default=0.0, verbose_name='Tempo Produção (min)')),
                ('tempo_parada', models.FloatField(default=0.0, verbose_name='Tempo Parada (min)')),
                ('tempo_setup', models.FloatField(default=0.0, verbose_name='Tempo Setup (min)')),
                ('disponibilidade', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disponibilidade (%)')),
                ('performance', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Performance (%)')),
                ('qualidade', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Qualidade (%)')),
                ('oee', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='OEE (%)')),
                ('calculado_em', models.DateTimeField(auto_now_add=True)),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='equipamentos.linhaproducao', verbose_name='Linha')),
            ],
            options={
                'verbose_name': 'Métrica de Produção',
                'verbose_name_plural': 'Métricas de Produção',
                'ordering': ['-data_hora'],
                'unique_together': {('linha', 'data_hora', 'periodo')},
            },
        ),
    ]
