# Generated by Django 5.0 on 2025-11-16 19:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConexaoOPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome da Conexão"
                    ),
                ),
                (
                    "url_servidor",
                    models.CharField(
                        help_text="Ex: opc.tcp://192.168.1.10:4840",
                        max_length=255,
                        verbose_name="URL do Servidor OPC",
                    ),
                ),
                (
                    "namespace_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Ex: ns=2;s=",
                        max_length=50,
                        verbose_name="Prefixo do Namespace",
                    ),
                ),
                (
                    "usuario",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Usuário"
                    ),
                ),
                (
                    "senha",
                    models.CharField(blank=True, max_length=100, verbose_name="Senha"),
                ),
                (
                    "timeout",
                    models.IntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Timeout (segundos)",
                    ),
                ),
                (
                    "ativa",
                    models.BooleanField(default=True, verbose_name="Conexão Ativa"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Conexão OPC",
                "verbose_name_plural": "Conexões OPC",
                "ordering": ["nome"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="metricaproducao",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="meta_oee",
            field=models.FloatField(
                default=85.0,
                help_text="Meta de OEE para o equipamento",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Meta OEE (%)",
            ),
        ),
        migrations.AddField(
            model_name="linhaproducao",
            name="meta_oee",
            field=models.FloatField(
                default=85.0,
                help_text="Meta de OEE para a linha",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Meta OEE (%)",
            ),
        ),
        migrations.AddField(
            model_name="metricaproducao",
            name="equipamento",
            field=models.ForeignKey(
                blank=True,
                help_text="Deixe em branco para métricas da linha inteira",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metricas",
                to="equipamentos.equipamento",
                verbose_name="Equipamento",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="metricaproducao",
            unique_together={("linha", "equipamento", "data_hora", "periodo")},
        ),
        migrations.CreateModel(
            name="TagColeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_metrica",
                    models.CharField(
                        help_text="Ex: velocidade_atual, contagem_descartes, estado_maquina",
                        max_length=100,
                        verbose_name="Nome da Métrica",
                    ),
                ),
                (
                    "node_id",
                    models.CharField(
                        help_text="Ex: ns=2;s=Linha1.Enchedora.Velocidade",
                        max_length=255,
                        verbose_name="Node ID",
                    ),
                ),
                (
                    "tipo_dado",
                    models.CharField(
                        choices=[
                            ("INT", "Inteiro"),
                            ("FLOAT", "Decimal"),
                            ("STRING", "Texto"),
                            ("BOOL", "Booleano"),
                        ],
                        default="FLOAT",
                        max_length=10,
                        verbose_name="Tipo de Dado",
                    ),
                ),
                (
                    "unidade",
                    models.CharField(blank=True, max_length=20, verbose_name="Unidade"),
                ),
                (
                    "fator_conversao",
                    models.FloatField(
                        default=1.0,
                        help_text="Multiplicador aplicado ao valor lido",
                        verbose_name="Fator de Conversão",
                    ),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="Tag Ativa")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "conexao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="equipamentos.conexaoopc",
                        verbose_name="Conexão OPC",
                    ),
                ),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags_coleta",
                        to="equipamentos.equipamento",
                        verbose_name="Equipamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag de Coleta",
                "verbose_name_plural": "Tags de Coleta",
                "ordering": ["equipamento", "nome_metrica"],
                "unique_together": {("equipamento", "nome_metrica")},
            },
        ),
    ]
