# Generated by Django 5.0 on 2025-11-20 05:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "equipamentos",
            "0002_conexaoopc_alter_metricaproducao_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TurnoProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex: Turno A, Turno B, Turno C",
                        max_length=50,
                        unique=True,
                        verbose_name="Nome do Turno",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Ex: A, B, C",
                        max_length=10,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("hora_inicio", models.TimeField(verbose_name="Hora de Início")),
                ("hora_fim", models.TimeField(verbose_name="Hora de Fim")),
                (
                    "duracao_horas",
                    models.FloatField(
                        help_text="Duração do turno em horas",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Duração (horas)",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Turno Ativo"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Turno de Produção",
                "verbose_name_plural": "Turnos de Produção",
                "ordering": ["hora_inicio"],
            },
        ),
        migrations.AddField(
            model_name="metricaproducao",
            name="tempo_disponivel",
            field=models.FloatField(default=0.0, verbose_name="Tempo Disponível (min)"),
        ),
        migrations.AddField(
            model_name="metricaproducao",
            name="tempo_nao_programado",
            field=models.FloatField(
                default=0.0, verbose_name="Tempo Não Programado (min)"
            ),
        ),
        migrations.AddField(
            model_name="metricaproducao",
            name="tempo_programado",
            field=models.FloatField(default=0.0, verbose_name="Tempo Programado (min)"),
        ),
        migrations.AlterField(
            model_name="metricaproducao",
            name="periodo",
            field=models.CharField(
                choices=[
                    ("HORA", "Hora"),
                    ("TURNO", "Turno"),
                    ("DIA", "Dia"),
                    ("SEMANA", "Semana"),
                    ("MES", "Mês"),
                    ("ANO", "Ano"),
                ],
                default="HORA",
                max_length=20,
                verbose_name="Período",
            ),
        ),
        migrations.AlterField(
            model_name="tagcoleta",
            name="nome_metrica",
            field=models.CharField(
                help_text="Ex: velocidade_atual, contagem_entrada, contagem_saida, estado",
                max_length=100,
                verbose_name="Nome da Métrica",
            ),
        ),
        migrations.CreateModel(
            name="EventoEstadoEquipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("RUN", "Produzindo"),
                            ("WAIT_PREV", "Aguardando equipamento anterior"),
                            ("BLOCK_NEXT", "Equipamento seguinte bloqueado"),
                            ("FAULT", "Falha"),
                            ("SETUP", "Setup / Troca SKU"),
                            ("TESTE_PROJ", "Teste de Projeto"),
                            ("AGUARD_MNT", "Aguardando Manutenção"),
                            ("MANUTENCAO", "Em Manutenção"),
                            ("FALTA_MAT", "Falta de Material"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("inicio", models.DateTimeField(db_index=True, verbose_name="Início")),
                (
                    "fim",
                    models.DateTimeField(
                        blank=True,
                        help_text="Null enquanto o evento estiver aberto",
                        null=True,
                        verbose_name="Fim",
                    ),
                ),
                (
                    "duracao_segundos",
                    models.IntegerField(
                        blank=True,
                        help_text="Calculado automaticamente ao fechar o evento",
                        null=True,
                        verbose_name="Duração (segundos)",
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("OPC", "OPC UA"),
                            ("MANUAL", "Manual"),
                            ("SISTEMA", "Sistema"),
                        ],
                        default="OPC",
                        max_length=20,
                        verbose_name="Origem",
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_estado",
                        to="equipamentos.equipamento",
                        verbose_name="Equipamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Estado",
                "verbose_name_plural": "Eventos de Estado",
                "ordering": ["-inicio"],
                "indexes": [
                    models.Index(
                        fields=["equipamento", "inicio"],
                        name="equipamento_equipam_1e6df9_idx",
                    ),
                    models.Index(
                        fields=["equipamento", "estado"],
                        name="equipamento_equipam_834eba_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CalendarioProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(db_index=True, verbose_name="Data")),
                (
                    "programado",
                    models.BooleanField(
                        default=True,
                        help_text="Se a linha deve produzir neste dia/turno",
                        verbose_name="Programado",
                    ),
                ),
                (
                    "meta_producao_turno",
                    models.IntegerField(
                        help_text="Meta de produção para este turno específico",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Meta de Produção do Turno",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "linha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendario",
                        to="equipamentos.linhaproducao",
                        verbose_name="Linha de Produção",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendario",
                        to="equipamentos.turnoproducao",
                        verbose_name="Turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendário de Produção",
                "verbose_name_plural": "Calendários de Produção",
                "ordering": ["-data", "linha", "turno"],
                "unique_together": {("data", "linha", "turno")},
            },
        ),
    ]
