# Generated by Django 5.2.8 on 2025-11-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "equipamentos",
            "0003_turnoproducao_metricaproducao_tempo_disponivel_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipamento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ENCHEDORA", "Enchedora"),
                    ("ROTULADORA", "Rotuladora"),
                    ("PALETIZADOR", "Paletizador"),
                    ("BALANCA", "Balança"),
                    ("ENCAIXOTADORA", "Encaixotadora"),
                    ("ENVOLVEDORA", "Envolvedora"),
                    ("TAMPADORA", "Tampadora"),
                    ("SELADORA", "Seladora"),
                    ("CODIFICADORA", "Codificadora"),
                    ("INSPETOR", "Inspetor de Qualidade"),
                    ("TRANSPORTADOR", "Transportador/Esteira"),
                    ("OUTRO", "Outro"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
