# Generated by Django 5.2.8 on 2025-11-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0004_alter_equipamento_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipamento",
            name="tipo",
            field=models.CharField(
                help_text="Tipo do equipamento. Sugestões: ENCHEDORA, PALETIZADOR, BALANCA, ENCAIXOTADORA, ENVOLVEDORA, CODIFICADORA, TRANSPORTADOR, ou crie um tipo personalizado",
                max_length=50,
                verbose_name="Tipo",
            ),
        ),
    ]
