# Generated by Django 5.2.8 on 2025-11-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0005_alter_equipamento_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricaproducao",
            name="formato_gramas",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peso unitário usado no cálculo de toneladas",
                max_digits=10,
                null=True,
                verbose_name="Formato (g)",
            ),
        ),
        migrations.AddField(
            model_name="metricaproducao",
            name="toneladas_produzidas",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Total de toneladas de produto bom (contagem_saida × formato / 1.000.000)",
                max_digits=12,
                verbose_name="Toneladas Produzidas",
            ),
        ),
        migrations.AddField(
            model_name="metricaproducao",
            name="vazao_real_ton_hora",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Toneladas por hora efetiva de produção",
                max_digits=10,
                verbose_name="Vazão Real (ton/h)",
            ),
        ),
        migrations.AddField(
            model_name="tagcoleta",
            name="formato",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peso unitário do produto em gramas (ex: 2200, 1600). Usado para calcular toneladas produzidas.",
                max_digits=10,
                null=True,
                verbose_name="Formato (gramas)",
            ),
        ),
        migrations.AlterField(
            model_name="tagcoleta",
            name="tipo_dado",
            field=models.CharField(
                choices=[
                    ("INT", "Inteiro"),
                    ("FLOAT", "Decimal"),
                    ("STRING", "Texto"),
                    ("BOOL", "Booleano"),
                ],
                default="INT",
                max_length=20,
                verbose_name="Tipo de Dado",
            ),
        ),
    ]
