# Generated by Django 5.2.8 on 2025-11-25 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0006_metricaproducao_formato_gramas_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoFalha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("MECANICA", "Falha Mecânica"),
                            ("ELETRICA", "Falha Elétrica"),
                            ("OPERACIONAL", "Erro Operacional"),
                            ("MATERIA_PRIMA", "Problema Matéria-Prima"),
                            ("QUALIDADE", "Problema de Qualidade"),
                            ("SETUP", "Setup/Troca"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        default="#FF0000",
                        help_text="Cor para visualização em gráficos (ex: #FF0000)",
                        max_length=7,
                        verbose_name="Cor (Hex)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Falha",
                "verbose_name_plural": "Tipos de Falha",
                "ordering": ["categoria", "nome"],
            },
        ),
        migrations.AddField(
            model_name="eventoestadoequipamento",
            name="toneladas_perdidas",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Toneladas perdidas durante este evento (calculado automaticamente)",
                max_digits=10,
                null=True,
                verbose_name="Toneladas Perdidas",
            ),
        ),
        migrations.AddField(
            model_name="linhaproducao",
            name="meta_toneladas_hora",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Meta de produção em toneladas por hora",
                max_digits=10,
                null=True,
                verbose_name="Meta Toneladas/Hora",
            ),
        ),
        migrations.AddField(
            model_name="linhaproducao",
            name="meta_toneladas_turno",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Meta de produção em toneladas por turno (8h)",
                max_digits=10,
                null=True,
                verbose_name="Meta Toneladas/Turno",
            ),
        ),
        migrations.AddField(
            model_name="eventoestadoequipamento",
            name="tipo_falha",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de falha (se estado=FAULT ou parada)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventos",
                to="equipamentos.tipofalha",
                verbose_name="Tipo de Falha",
            ),
        ),
    ]
