# Generated by Django 5.0 on 2025-11-25 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "equipamentos",
            "0007_tipofalha_eventoestadoequipamento_toneladas_perdidas_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome da Área")),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
                "ordering": ["fabrica", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Fabrica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Fábrica"),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                (
                    "localizacao",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Localização"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fábrica",
                "verbose_name_plural": "Fábricas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código SKU"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "peso_unitario",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Peso do produto em gramas",
                        max_digits=10,
                        verbose_name="Peso Unitário (g)",
                    ),
                ),
                (
                    "fator_conversao",
                    models.FloatField(
                        default=1.0,
                        help_text="Fator para converter unidades em caixas/fardos se necessário",
                        verbose_name="Fator de Conversão",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Produto (SKU)",
                "verbose_name_plural": "Produtos (SKUs)",
                "ordering": ["codigo"],
            },
        ),
        migrations.AddField(
            model_name="metricaproducao",
            name="toneladas_hora",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Toneladas produzidas na hora cheia",
                max_digits=10,
                verbose_name="Toneladas/Hora (Absoluto)",
            ),
        ),
        migrations.AddField(
            model_name="linhaproducao",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linhas",
                to="equipamentos.area",
                verbose_name="Área",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="fabrica",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="equipamentos.fabrica",
                verbose_name="Fábrica",
            ),
        ),
        migrations.AddField(
            model_name="metricaproducao",
            name="produto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="metricas",
                to="equipamentos.produto",
                verbose_name="Produto (SKU)",
            ),
        ),
        migrations.CreateModel(
            name="HistoricoSKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(db_index=True, verbose_name="Data Início"),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Fim"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "linha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_skus",
                        to="equipamentos.linhaproducao",
                        verbose_name="Linha",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_linhas",
                        to="equipamentos.produto",
                        verbose_name="Produto (SKU)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de SKU",
                "verbose_name_plural": "Histórico de SKUs",
                "ordering": ["-data_inicio"],
                "indexes": [
                    models.Index(
                        fields=["linha", "data_inicio"],
                        name="equipamento_linha_i_c01860_idx",
                    )
                ],
            },
        ),
    ]
