# Generated by Django 5.2.8 on 2025-11-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "equipamentos",
            "0008_area_fabrica_produto_metricaproducao_toneladas_hora_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicosku",
            name="meta_producao",
            field=models.IntegerField(default=0, verbose_name="Meta de Produção"),
        ),
        migrations.AddField(
            model_name="historicosku",
            name="ordem_producao",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Ordem de Produção"
            ),
        ),
        migrations.AddField(
            model_name="metricaproducao",
            name="meta_producao",
            field=models.IntegerField(default=0, verbose_name="Meta de Produção"),
        ),
        migrations.AddField(
            model_name="metricaproducao",
            name="ordem_producao",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Ordem de Produção"
            ),
        ),
    ]
