# Generated by Django 5.2.8 on 2025-11-26 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0009_historicosku_meta_producao_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="metricaproducao",
            unique_together={
                (
                    "linha",
                    "equipamento",
                    "data_hora",
                    "periodo",
                    "produto",
                    "ordem_producao",
                )
            },
        ),
    ]
