# Generated by Django 5.2.8 on 2025-11-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0010_alter_metricaproducao_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="linhaproducao",
            name="tecnologia",
            field=models.CharField(
                choices=[
                    ("CARTUCHO", "Cartucho"),
                    ("FLEXIVEL", "Flexível"),
                    ("OUTROS", "Outros"),
                ],
                default="OUTROS",
                max_length=20,
                verbose_name="Tecnologia / Categoria",
            ),
        ),
    ]
