# Generated by Django 5.2.8 on 2025-11-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0011_linhaproducao_tecnologia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linhaproducao",
            name="tecnologia",
        ),
        migrations.AddField(
            model_name="historicosku",
            name="producao_realizada",
            field=models.DecimalField(
                decimal_places=3,
                default=0.0,
                max_digits=12,
                verbose_name="Produção Realizada (ton)",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="metricaproducao",
            unique_together={("linha", "equipamento", "data_hora", "periodo")},
        ),
    ]
