# Generated by Django 5.2.8 on 2025-11-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0012_remove_linhaproducao_tecnologia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoParada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maquina", models.CharField(max_length=50)),
                ("op", models.CharField(max_length=50)),
                ("turno", models.CharField(max_length=1)),
                ("sku", models.CharField(max_length=50)),
                ("inicio", models.DateTimeField()),
                ("fim", models.DateTimeField(blank=True, null=True)),
                ("duracao_segundos", models.IntegerField(default=0)),
                ("toneladas_perdidas", models.FloatField(default=0.0)),
                (
                    "categoria_clp",
                    models.CharField(
                        choices=[
                            ("RUN", "Produzindo"),
                            ("STOP_MANUAL", "Parada Manual"),
                            ("FAIL_MEC", "Falha Mecânica"),
                            ("FAIL_ELE", "Falha Elétrica"),
                            ("STARVED", "Falta de Entrada (Starved)"),
                            ("BLOCKED", "Bloqueio de Saída (Blocked)"),
                            ("SETUP", "Setup/Troca"),
                            ("QUALIDADE", "Problema de Qualidade"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detalhe_operador", models.TextField(blank=True, null=True)),
                ("justificado", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "eventos_parada",
                "indexes": [
                    models.Index(
                        fields=["inicio", "fim"], name="eventos_par_inicio_22364a_idx"
                    ),
                    models.Index(fields=["op"], name="eventos_par_op_4fa372_idx"),
                ],
            },
        ),
    ]
