# Generated by Django 5.2.8 on 2025-11-27 17:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0013_eventoparada"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdemProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Código da OP",
                    ),
                ),
                (
                    "meta_total",
                    models.IntegerField(
                        help_text="Meta total de produção para esta OP",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Meta Total",
                    ),
                ),
                (
                    "meta_turno",
                    models.IntegerField(
                        help_text="Meta de produção por turno",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Meta por Turno",
                    ),
                ),
                (
                    "formato_gramas",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Peso unitário do produto em gramas",
                        max_digits=10,
                        verbose_name="Formato (gramas)",
                    ),
                ),
                (
                    "cuc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Custo Unitário de Conversão",
                        max_digits=10,
                        null=True,
                        verbose_name="CUC",
                    ),
                ),
                (
                    "eficiencia_planejada",
                    models.FloatField(
                        default=85.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Eficiência Planejada (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANEJADA", "Planejada"),
                            ("PRODUZINDO", "Em Produção"),
                            ("PAUSADA", "Pausada"),
                            ("CONCLUIDA", "Concluída"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PLANEJADA",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_planejada_inicio",
                    models.DateTimeField(verbose_name="Data Planejada de Início"),
                ),
                (
                    "data_inicio_real",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Real de Início"
                    ),
                ),
                (
                    "data_fim_real",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Real de Término"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "linha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordens_producao",
                        to="equipamentos.linhaproducao",
                        verbose_name="Linha de Produção",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordens_producao",
                        to="equipamentos.produto",
                        verbose_name="Produto (SKU)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de Produção",
                "verbose_name_plural": "Ordens de Produção",
                "ordering": ["-data_planejada_inicio"],
            },
        ),
        migrations.CreateModel(
            name="RegistroProducaoTurno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(db_index=True, verbose_name="Data (Dia Contábil)"),
                ),
                (
                    "producao_unidades",
                    models.IntegerField(
                        default=0,
                        help_text="Total de unidades produzidas no turno",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Produção (unidades)",
                    ),
                ),
                (
                    "producao_toneladas",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Total de toneladas produzidas no turno",
                        max_digits=12,
                        verbose_name="Produção (toneladas)",
                    ),
                ),
                (
                    "refugo_unidades",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Refugo (unidades)",
                    ),
                ),
                (
                    "refugo_kg",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Refugo (kg)",
                    ),
                ),
                (
                    "tempo_programado_min",
                    models.FloatField(
                        help_text="Tempo total programado para o turno",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tempo Programado (min)",
                    ),
                ),
                (
                    "tempo_disponivel_min",
                    models.FloatField(
                        help_text="Tempo programado - tempo não programado",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tempo Disponível (min)",
                    ),
                ),
                (
                    "tempo_producao_min",
                    models.FloatField(
                        help_text="Tempo efetivo em produção (estado RUN)",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tempo Produção (min)",
                    ),
                ),
                (
                    "tempo_parado_min",
                    models.FloatField(
                        default=0,
                        help_text="Tempo de paradas não planejadas",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tempo Parado (min)",
                    ),
                ),
                (
                    "tempo_setup_min",
                    models.FloatField(
                        default=0,
                        help_text="Tempo de setup/troca de SKU",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tempo Setup (min)",
                    ),
                ),
                (
                    "disponibilidade",
                    models.FloatField(
                        default=0,
                        help_text="A = (Tempo Produção / Tempo Disponível) × 100",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Disponibilidade (%)",
                    ),
                ),
                (
                    "performance",
                    models.FloatField(
                        default=0,
                        help_text="P = (Produção Real / Produção Planejada) × 100",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Performance (%)",
                    ),
                ),
                (
                    "qualidade",
                    models.FloatField(
                        default=0,
                        help_text="Q = (Produção Boa / Produção Total) × 100",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Qualidade (%)",
                    ),
                ),
                (
                    "oee",
                    models.FloatField(
                        default=0,
                        help_text="OEE = (A × P × Q) / 10000",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="OEE (%)",
                    ),
                ),
                (
                    "eficiencia",
                    models.FloatField(
                        default=0,
                        help_text="Razão entre produção real e meta",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Eficiência (%)",
                    ),
                ),
                (
                    "velocidade_media",
                    models.FloatField(
                        default=0,
                        help_text="Velocidade média durante o turno",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Velocidade Média (unid/min)",
                    ),
                ),
                (
                    "velocidade_planejada",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Velocidade Planejada (unid/min)",
                    ),
                ),
                (
                    "consolidado_em",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp de quando este registro foi criado",
                        verbose_name="Consolidado em",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "linha",
                    models.ForeignKey(
                        help_text="Redundante mas útil para performance de queries",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_turno",
                        to="equipamentos.linhaproducao",
                        verbose_name="Linha",
                    ),
                ),
                (
                    "ordem_producao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_turno",
                        to="equipamentos.ordemproducao",
                        verbose_name="Ordem de Produção",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_turno",
                        to="equipamentos.produto",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_producao",
                        to="equipamentos.turnoproducao",
                        verbose_name="Turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Produção por Turno",
                "verbose_name_plural": "Registros de Produção por Turno",
                "ordering": ["-data", "turno"],
            },
        ),
        migrations.AddIndex(
            model_name="ordemproducao",
            index=models.Index(fields=["codigo"], name="equipamento_codigo_5dd525_idx"),
        ),
        migrations.AddIndex(
            model_name="ordemproducao",
            index=models.Index(fields=["status"], name="equipamento_status_b51aef_idx"),
        ),
        migrations.AddIndex(
            model_name="ordemproducao",
            index=models.Index(
                fields=["linha", "status"], name="equipamento_linha_i_b8c554_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registroproducaoturno",
            index=models.Index(
                fields=["data", "turno"], name="equipamento_data_6bc96b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registroproducaoturno",
            index=models.Index(
                fields=["linha", "data"], name="equipamento_linha_i_03ee35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registroproducaoturno",
            index=models.Index(
                fields=["ordem_producao"], name="equipamento_ordem_p_e64e4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registroproducaoturno",
            index=models.Index(
                fields=["data", "linha", "turno"], name="equipamento_data_de5095_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="registroproducaoturno",
            unique_together={("ordem_producao", "data", "turno")},
        ),
    ]
