# Generated by Django 5.2.8 on 2025-11-27 21:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0014_ordemproducao_registroproducaoturno_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordemproducao",
            name="meta_turno",
        ),
    ]
