# Generated by Django 5.2.8 on 2025-11-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0015_remove_ordemproducao_meta_turno"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemproducao",
            name="producao_realizada",
            field=models.DecimalField(
                decimal_places=3,
                default=0.0,
                help_text="Total produzido acumulado para esta OP",
                max_digits=12,
                verbose_name="Produção Realizada (ton)",
            ),
        ),
    ]
