# Generated by Django 5.2.8 on 2025-11-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0017_strategicinitiative"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipamento",
            name="codigo",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="Código"
            ),
        ),
        migrations.AlterField(
            model_name="fabrica",
            name="codigo",
            field=models.CharField(
                blank=True, max_length=20, unique=True, verbose_name="Código"
            ),
        ),
    ]
