# Generated by Django 5.0 on 2025-12-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0018_alter_equipamento_codigo_alter_fabrica_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("INPUT_BOOL", "Input Digital (Booleano)"),
                    ("INPUT_FLOAT", "Input Analógico (Decimal)"),
                    ("INPUT_INT", "Input Inteiro"),
                    ("TIMER", "Temporizador (Tempo)"),
                    ("COUNTER", "Contador"),
                    ("SETPOINT", "Setpoint / Ajuste"),
                    ("LIMIT", "Limite / Parâmetro"),
                    ("OUTRO", "Outro"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AddIndex(
            model_name="calendarioproducao",
            index=models.Index(
                fields=["data", "turno"], name="equipamento_data_ad9d78_idx"
            ),
        ),
    ]
