# Generated by Django 5.0 on 2025-12-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0020_sensor_lsl_sensor_nominal_sensor_usl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='is_parameter',
            field=models.BooleanField(default=False, help_text='Se marcado, este sensor será tratado como um parâmetro ajustável no Golden State (Write-Back).', verbose_name='É Parâmetro de Máquina?'),
        ),
        migrations.AlterField(
            model_name='eventoestadoequipamento',
            name='estado',
            field=models.CharField(choices=[('RUN', 'Produzindo'), ('PARTINDO', 'Partindo'), ('PARANDO', 'Parando'), ('WAIT_PREV', 'Aguardando equipamento anterior'), ('BLOCK_NEXT', 'Equipamento seguinte bloqueado'), ('FAULT', 'Falha'), ('SETUP', 'Setup / Troca SKU'), ('TESTE_PROJ', 'Teste de Projeto'), ('AGUARD_MNT', 'Aguardando Manutenção'), ('MANUTENCAO', 'Em Manutenção'), ('FALTA_MAT', 'Falta de Material'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Estado'),
        ),
    ]
