# Generated by Django 5.0 on 2025-12-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0021_sensor_is_parameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='is_parameter',
        ),
    ]
