# Generated by Django 5.0 on 2025-12-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0022_remove_sensor_is_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipofalha',
            name='categoria',
            field=models.CharField(choices=[('MECANICA', 'Falha Mecânica'), ('ELETRICA', 'Falha Elétrica'), ('OPERACIONAL', 'Erro Operacional'), ('MATERIA_PRIMA', 'Problema Matéria-Prima'), ('QUALIDADE', 'Problema de Qualidade'), ('SETUP', 'Setup/Troca'), ('SETPOINT', 'Set Point'), ('LIMIT', 'Limite de Processo'), ('HEARTBEAT', 'Health Check'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Categoria'),
        ),
    ]
