# Generated by Django 5.0 on 2025-12-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0023_alter_tipofalha_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='tipo',
            field=models.CharField(choices=[('INPUT_BOOL', 'Input Digital (Booleano)'), ('INPUT_FLOAT', 'Input Analógico (Decimal)'), ('INPUT_INT', 'Input Inteiro'), ('TIMER', 'Temporizador (Tempo)'), ('COUNTER', 'Contador'), ('SETPOINT', 'Setpoint / Ajuste'), ('LIMIT', 'Limite / Parâmetro'), ('HEARTBEAT', 'Health Check'), ('COMM_ERROR', 'Erro de Comunicação'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo'),
        ),
    ]
