# Generated by Django 5.0 on 2025-12-26 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0024_alter_sensor_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexaoopc',
            name='tag_monitoramento',
            field=models.CharField(blank=True, help_text='NodeID da tag de saúde (Ex: ns=2;s=Line1.Heartbeat ou Line1.Error)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conexaoopc',
            name='tipo_monitoramento',
            field=models.CharField(choices=[('HEARTBEAT', 'Pulse (Heartbeat)'), ('ERROR_BOOL', 'Bit de Erro (True=Error)')], default='HEARTBEAT', help_text='Como interpretar a tag de monitoramento', max_length=20, verbose_name='Tipo de Monitoramento'),
        ),
        migrations.AddField(
            model_name='linhaproducao',
            name='conexao_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linhas', to='equipamentos.conexaoopc', verbose_name='Conexão OPC Padrão'),
        ),
    ]
