# Generated by Django 5.0 on 2025-12-26 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0025_conexaoopc_tag_monitoramento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcoleta',
            name='conexao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='equipamentos.conexaoopc', verbose_name='Conexão OPC'),
        ),
    ]
