# Generated by Django 5.0 on 2025-12-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0026_alter_tagcoleta_conexao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagcoleta',
            name='conexao',
        ),
    ]
