# Generated by Django 5.0 on 2026-02-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0027_remove_tagcoleta_conexao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linhaproducao',
            options={'ordering': ['area', 'nome'], 'verbose_name': 'Linha de Produção', 'verbose_name_plural': 'Linhas de Produção'},
        ),
    ]
