# Generated by Django 5.0 on 2026-05-17 18:46

from django.db import migrations, models


def seed_golden_from_specs(apps, schema_editor):
    """Heurística inicial: sensores com LSL/USL definidos (já sinalizam
    "variável controlada com especificação") entram como golden_state=True.
    Coordenador ajusta depois caso a caso no admin.
    """
    Sensor = apps.get_model('equipamentos', 'Sensor')
    Sensor.objects.filter(lsl__isnull=False).update(golden_state=True)
    Sensor.objects.filter(usl__isnull=False).update(golden_state=True)


def revert_golden(apps, schema_editor):
    Sensor = apps.get_model('equipamentos', 'Sensor')
    Sensor.objects.update(golden_state=False)


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0035_giveaway_peso_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='golden_state',
            field=models.BooleanField(default=False, help_text='Marque quando este sensor define a "condição ótima" de operação (setpoint de receita, parâmetro controlado). Leituras puras de ambiente NÃO devem ser marcadas.', verbose_name='Golden State'),
        ),
        migrations.AddField(
            model_name='tagcoleta',
            name='golden_state',
            field=models.BooleanField(default=False, help_text='Marque quando esta variável define a "condição ótima" de operação (setpoints, parâmetros de receita). Variáveis de leitura pura como temperaturas ambiente NÃO devem ser marcadas.', verbose_name='Golden State'),
        ),
        migrations.RunPython(seed_golden_from_specs, revert_golden),
    ]
