# Generated by Django 5.0 on 2026-05-17 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0036_golden_state_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldenStateRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Ex: "Turno A do dia 17/05" — usado em listas.', max_length=120, verbose_name='Nome curto')),
                ('sku_codigo', models.CharField(blank=True, help_text='SKU rodando na janela. Vazio = qualquer SKU.', max_length=60, null=True, verbose_name='SKU rodando')),
                ('fonte', models.CharField(choices=[('AUTO', 'Automático (turno bom detectado)'), ('MANUAL', 'Capturado manualmente')], default='MANUAL', max_length=10, verbose_name='Fonte')),
                ('inicio', models.DateTimeField(verbose_name='Início da janela')),
                ('fim', models.DateTimeField(verbose_name='Fim da janela')),
                ('score', models.FloatField(blank=True, help_text='Score combinado de produção/qualidade/estabilidade.', null=True, verbose_name='Score (0-100)')),
                ('tph_medio', models.FloatField(blank=True, null=True, verbose_name='TPH médio')),
                ('refugo_pct', models.FloatField(blank=True, null=True, verbose_name='% Refugo')),
                ('oee_medio', models.FloatField(blank=True, null=True, verbose_name='OEE médio')),
                ('observacoes', models.TextField(blank=True, help_text='Anotação livre do coordenador: "depois do ajuste de pressão", etc.', verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para excluir esta corrida do cálculo da receita.', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.CharField(blank=True, help_text='Placeholder; preenchido com username quando houver auth.', max_length=120, verbose_name='Criado por')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golden_state_runs', to='equipamentos.linhaproducao', verbose_name='Linha')),
            ],
            options={
                'verbose_name': 'Corrida de referência (Golden State)',
                'verbose_name_plural': 'Corridas de referência (Golden State)',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='GoldenStateVarSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_amigavel', models.CharField(max_length=120)),
                ('tag_influx', models.CharField(max_length=120)),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('equipamento_codigo', models.CharField(blank=True, max_length=20)),
                ('p10', models.FloatField()),
                ('p50', models.FloatField()),
                ('p90', models.FloatField()),
                ('n_amostras', models.IntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaveis', to='equipamentos.goldenstaterun')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipamentos.sensor')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipamentos.tagcoleta')),
            ],
            options={
                'verbose_name': 'Snapshot de variável (Golden State)',
                'verbose_name_plural': 'Snapshots de variáveis (Golden State)',
                'ordering': ['nome_amigavel'],
            },
        ),
        migrations.AddConstraint(
            model_name='goldenstaterun',
            constraint=models.UniqueConstraint(condition=models.Q(('fonte', 'AUTO')), fields=('linha', 'sku_codigo', 'inicio'), name='uniq_golden_auto_linha_sku_inicio'),
        ),
    ]
