# Generated by Django 5.0 on 2026-05-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0037_golden_state_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenstaterun',
            name='formato_gramas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso unitário do produto na janela. Permite filtrar receita por formato (ex: SKUs diferentes mas mesmo formato compartilham receita).', max_digits=10, null=True, verbose_name='Formato (g)'),
        ),
    ]
