# Generated by Django 5.0 on 2026-05-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0038_golden_run_formato_gramas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Ferramenta externa (permissão)',
                'verbose_name_plural': 'Ferramentas externas (permissões)',
                'permissions': [('access_nodered', 'Pode acessar Node-RED'), ('access_grafana', 'Pode acessar Grafana'), ('access_chronograf', 'Pode acessar Chronograf'), ('access_emqx', 'Pode acessar EMQX Dashboard')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
