# Generated by Django 5.0 on 2026-05-19 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0039_external_tools_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeRedSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario_nome', models.CharField(blank=True, help_text='Preservado mesmo se o usuário for deletado.', max_length=150, verbose_name='Username (cache)')),
                ('acao', models.CharField(choices=[('DEPLOY', 'Deploy (alteração do editor)'), ('RESTORE', 'Restauração de versão anterior'), ('INITIAL', 'Snapshot inicial')], default='DEPLOY', max_length=10, verbose_name='Ação')),
                ('descricao', models.CharField(blank=True, help_text='Mensagem opcional (ex.: "Adicionado fluxo de alarmes E001").', max_length=200, verbose_name='Descrição')),
                ('flows_json', models.JSONField(help_text='Snapshot integral do flows.json no momento do deploy.', verbose_name='Fluxograma completo (JSON)')),
                ('hash_sha', models.CharField(db_index=True, help_text='Hash do flows_json — usado para detectar duplicatas.', max_length=64, verbose_name='SHA-256')),
                ('num_nodes', models.IntegerField(default=0, verbose_name='Nº de nós')),
                ('size_bytes', models.IntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('nodes_adicionados', models.IntegerField(default=0)),
                ('nodes_removidos', models.IntegerField(default=0)),
                ('nodes_modificados', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, help_text='Cadeia linear: snapshot anterior na linha do tempo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos', to='equipamentos.noderedsnapshot', verbose_name='Versão anterior')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodered_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável')),
            ],
            options={
                'verbose_name': 'Snapshot Node-RED',
                'verbose_name_plural': 'Histórico Node-RED',
                'ordering': ['-criado_em'],
            },
        ),
    ]
