persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log

# Ouvir em todas as interfaces (importante para Docker)
listener 1883
allow_anonymous true

# WebSockets (opcional, bom para dashboards web diretos)
listener 9001
protocol websockets
