server {
    listen 80;
    # Aumente o client_max_body_size se você espera uploads de arquivos grandes
    # client_max_body_size 10M; # Exemplo

    # Define o root para os arquivos estáticos da sua aplicação React
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Tenta servir o arquivo diretamente, se não encontrar, redireciona para index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Configurações de cache para arquivos estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Opcional: Configurações para arquivos de fonte
    location ~* \.(ttf|ttc|otf|eot|woff|woff2|font.css)$ {
        add_header Access-Control-Allow-Origin "*";
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Opcional: Desabilitar o cache para HTML
    location ~* \.(html)$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    # Opcional: Proxy para o seu backend (se você não usar um gateway API separado ou Docker Compose)
    # No entanto, em um ambiente Docker Compose, a comunicação geralmente é entre os serviços.
    # Se você está separando frontend e backend, o frontend se comunicará diretamente com o serviço do backend.
    # location /api/ {
    #     proxy_pass http://seu_backend_host:8000/api/;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    # }
}