server {
    listen 80;
    index index.html index.htm;

    # Redirecionar raiz para /mis-change-over/
    location = / {
        return 302 /mis-change-over/;
    }

    # Servir a aplicacao React sob o prefixo /mis-change-over/
    location /mis-change-over/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /mis-change-over/index.html;
    }
}