import { useState, useEffect } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import {
  Activity,
  AlertCircle,
  CheckCircle,
  Database,
  RefreshCw,
  TrendingUp,
  Zap,
  Clock
} from 'lucide-react'
import { api } from '@/lib/api'

const AutoTraining = ({ selectedLine }) => {
  const [syncStatus, setSyncStatus] = useState(null)
  const [autoGeneratedData, setAutoGeneratedData] = useState([])
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    if (selectedLine) {
      loadData()
      // Auto-refresh a cada 5 segundos
      const interval = setInterval(loadData, 5000)
      return () => clearInterval(interval)
    }
  }, [selectedLine])

  const loadData = async () => {
    if (!selectedLine) return
    setLoading(true)
    try {
      const [status, data] = await Promise.all([
        api.getReferenceSyncStatus(),
        api.getAutoGeneratedData({ line: selectedLine, limit: 100 })
      ])
      setSyncStatus(status)
      setAutoGeneratedData(data || [])
    } catch (error) {
      console.error("Erro ao carregar dados:", error)
    } finally {
      setLoading(false)
    }
  }

  if (!selectedLine) {
    return (
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold">Treinamento Automático</h1>
          <p className="text-muted-foreground">
            Monitoramento de captura automática de dados para treinamento contínuo
          </p>
        </div>
        <Card>
          <CardContent className="text-center py-12">
            <AlertCircle className="h-12 w-12 mx-auto mb-4 text-muted-foreground opacity-50" />
            <h3 className="text-lg font-semibold mb-2">Nenhuma linha selecionada</h3>
            <p className="text-muted-foreground">
              Selecione uma linha na barra de navegação para visualizar o status de sincronização.
            </p>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold flex items-center space-x-3">
            <Zap className="h-8 w-8 text-yellow-600" />
            <span>Treinamento Automático</span>
          </h1>
          <p className="text-muted-foreground mt-1">
            Linha: <strong>{selectedLine}</strong> | Captura automática de dados de referência
          </p>
        </div>
        <div className="flex items-center space-x-2">
          {loading && <RefreshCw className="h-5 w-5 animate-spin text-blue-600" />}
          <Badge variant={syncStatus?.is_running ? 'default' : 'secondary'} className="flex items-center space-x-1">
            {syncStatus?.is_running ? (
              <>
                <Activity className="h-3 w-3 animate-pulse" />
                <span>Sincronizando</span>
              </>
            ) : (
              <>
                <Clock className="h-3 w-3" />
                <span>Pausado</span>
              </>
            )}
          </Badge>
        </div>
      </div>

      {/* Status Cards - ISA-101 Style */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card className="border-2 border-yellow-300 dark:border-yellow-700 bg-gradient-to-br from-yellow-50 to-amber-50 dark:from-yellow-950/20 dark:to-amber-950/20">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-yellow-700 dark:text-yellow-400 flex items-center space-x-2">
              <Activity className="h-4 w-4" />
              <span>Status do Sync</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {syncStatus?.is_running ? (
                <span className="text-green-600 flex items-center space-x-2">
                  <CheckCircle className="h-6 w-6" />
                  <span>Ativo</span>
                </span>
              ) : (
                <span className="text-gray-600 flex items-center space-x-2">
                  <AlertCircle className="h-6 w-6" />
                  <span>Inativo</span>
                </span>
              )}
            </div>
          </CardContent>
        </Card>

        <Card className="border-2 border-blue-300 dark:border-blue-700">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-blue-700 dark:text-blue-400 flex items-center space-x-2">
              <Database className="h-4 w-4" />
              <span>Variáveis Reference</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-blue-600">
              {syncStatus?.reference_variables_count || 0}
            </div>
            <p className="text-xs text-muted-foreground mt-1">Configuradas</p>
          </CardContent>
        </Card>

        <Card className="border-2 border-green-300 dark:border-green-700">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-green-700 dark:text-green-400 flex items-center space-x-2">
              <TrendingUp className="h-4 w-4" />
              <span>Dados Capturados</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-600">
              {autoGeneratedData.length}
            </div>
            <p className="text-xs text-muted-foreground mt-1">Últimos 100 registros</p>
          </CardContent>
        </Card>

        <Card className="border-2 border-purple-300 dark:border-purple-700">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-purple-700 dark:text-purple-400 flex items-center space-x-2">
              <Clock className="h-4 w-4" />
              <span>Última Captura</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-sm font-mono text-purple-600">
              {syncStatus?.last_sync
                ? new Date(syncStatus.last_sync_time).toLocaleTimeString('pt-BR')
                : 'N/A'}
            </div>
            <p className="text-xs text-muted-foreground mt-1">
              {syncStatus?.last_sync_time
                ? `${Math.floor((Date.now() - new Date(syncStatus.last_sync_time)) / 1000)}s atrás`
                : 'Aguardando...'}
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Informações sobre o Sistema */}
      <Card className="border-l-4 border-l-yellow-500">
        <CardHeader>
          <CardTitle className="flex items-center space-x-2 text-yellow-700 dark:text-yellow-400">
            <Zap className="h-5 w-5" />
            <span>Como Funciona o Treinamento Automático</span>
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 text-sm">
          <div className="flex items-start space-x-3">
            <div className="bg-yellow-100 dark:bg-yellow-900 rounded-full p-2">
              <span className="font-bold text-yellow-700 dark:text-yellow-300">1</span>
            </div>
            <div>
              <p className="font-semibold">Configuração de Variáveis Reference</p>
              <p className="text-muted-foreground">
                Variáveis OPC do tipo "Referência" são associadas a um target específico e monitoradas continuamente.
              </p>
            </div>
          </div>
          <div className="flex items-start space-x-3">
            <div className="bg-yellow-100 dark:bg-yellow-900 rounded-full p-2">
              <span className="font-bold text-yellow-700 dark:text-yellow-300">2</span>
            </div>
            <div>
              <p className="font-semibold">Captura Automática</p>
              <p className="text-muted-foreground">
                A cada 5 segundos, o sistema lê automaticamente os valores das variáveis reference e das variáveis de input (read).
              </p>
            </div>
          </div>
          <div className="flex items-start space-x-3">
            <div className="bg-yellow-100 dark:bg-yellow-900 rounded-full p-2">
              <span className="font-bold text-yellow-700 dark:text-yellow-300">3</span>
            </div>
            <div>
              <p className="font-semibold">Armazenamento Inteligente</p>
              <p className="text-muted-foreground">
                Os dados são salvos automaticamente no banco como registros de treinamento, prontos para retreinamento do modelo.
              </p>
            </div>
          </div>
          <div className="flex items-start space-x-3">
            <div className="bg-yellow-100 dark:bg-yellow-900 rounded-full p-2">
              <span className="font-bold text-yellow-700 dark:text-yellow-300">4</span>
            </div>
            <div>
              <p className="font-semibold">Retreinamento Contínuo</p>
              <p className="text-muted-foreground">
                Quando o número de registros atinge o limite configurado, o modelo é retreinado automaticamente com os novos dados.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Tabela de Dados Capturados */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center space-x-2">
            <Database className="h-5 w-5 text-blue-600" />
            <span>Dados Capturados Automaticamente</span>
          </CardTitle>
          <CardDescription>
            Últimos 100 registros gerados pela sincronização automática
          </CardDescription>
        </CardHeader>
        <CardContent>
          {autoGeneratedData.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              <Database className="h-12 w-12 mx-auto mb-3 opacity-50" />
              <p>Nenhum dado capturado ainda</p>
              <p className="text-sm mt-2">Configure variáveis do tipo "Referência" para iniciar a captura automática</p>
            </div>
          ) : (
            <div className="max-h-[500px] overflow-y-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Data/Hora</TableHead>
                    <TableHead>Target</TableHead>
                    <TableHead>Valor Medido</TableHead>
                    <TableHead>Features Capturadas</TableHead>
                    <TableHead>Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {autoGeneratedData.map((data, index) => (
                    <TableRow key={data.id || index} className="hover:bg-yellow-50 dark:hover:bg-yellow-950/20">
                      <TableCell className="font-mono text-xs">
                        {new Date(data.timestamp || data.created_at).toLocaleString('pt-BR')}
                      </TableCell>
                      <TableCell className="font-medium">
                        {data.target_name || 'N/A'}
                      </TableCell>
                      <TableCell>
                        <span className="font-mono text-sm font-bold text-blue-600">
                          {data.measured_value?.toFixed(2) || 'N/A'}
                        </span>
                      </TableCell>
                      <TableCell>
                        <div className="flex flex-wrap gap-1">
                          {data.features && Object.keys(data.features).length > 0 ? (
                            Object.entries(data.features).slice(0, 3).map(([key, value]) => (
                              <Badge key={key} variant="outline" className="text-xs">
                                {key}: {typeof value === 'number' ? value.toFixed(2) : value}
                              </Badge>
                            ))
                          ) : (
                            <span className="text-xs text-muted-foreground">Sem features</span>
                          )}
                          {data.features && Object.keys(data.features).length > 3 && (
                            <Badge variant="secondary" className="text-xs">
                              +{Object.keys(data.features).length - 3}
                            </Badge>
                          )}
                        </div>
                      </TableCell>
                      <TableCell>
                        <Badge className="bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200 flex items-center space-x-1 w-fit">
                          <CheckCircle className="h-3 w-3" />
                          <span>Capturado</span>
                        </Badge>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}

export default AutoTraining
